VERSION 0.6

rust:
  FROM debian:bullseye
  ARG toolchain
  RUN [ ! -z "$toolchain" ] || exit 1
  RUN apt update -y && apt upgrade -y
  RUN apt install gcc make build-essential curl -y
  RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $toolchain
  ENV PATH=/root/.cargo/bin:"$PATH"

application:
  FROM +rust
  WORKDIR /app
  COPY . .

image:
  ARG toolchain
  ARG version
  ARG tag
  FROM DOCKERFILE \
    -f ./docker/Dockerfile \
    --build-arg toolchain=$toolchain \
    --build-arg version=$version \
    ../../
  SAVE IMAGE $tag

fmt:
  FROM +application
  RUN cargo fmt --all -- --check

test:
  FROM +application
  ARG features
  RUN cargo test $features
