version: 0.1.0

server:
  address: "0.0.0.0:8080"
  heartbeats: 10
  connection_timeout: 31
  stats: 10

redis:
  endpoint: "redis://redis:6379"

routes:
  authorizer:
    endpoint: "http://authorizer:8080"
    headers:
      Authorization: sugarhowyougetsofly
  connect:
    endpoint: "http://connect:8080"
    headers:
      Authorization: sugarhowyougetsofly
  disconnect:
    endpoint: "http://disconnect:8080"
    headers:
      Authorization: sugarhowyougetsofly
  rules_engine:
    endpoint: "http://rulesengine:8080"
    headers:
      Authorization: sugarhowyougetsofly
