version: 0.1.0

server:
  address: "0.0.0.0:8080"
  heartbeat_interval_sec: 10
  connection_timeout_sec: 31
  stats_interval_sec: 10
  max_out_message_size: 262144 # 256kb

redis:
  endpoint: "redis://redis:6379"

routes:
  rules_engine:
    endpoint: "http://rulesengine:8080"
    headers:
      Authorization: some-key
  # authorizer:
  #   endpoint: "http://authorizer:8080"
  #   headers:
  #     Authorization: some-key
  # connect:
  #   endpoint: "http://connect:8080"
  #   headers:
  #     Authorization: some-key
  # disconnect:
  #   endpoint: "http://disconnect:8080"
  #   headers:
  #     Authorization: some-key
