apiVersion: apps/v1
kind: Deployment
metadata:
  name: spoderman
spec:
  selector:
    matchLabels:
      app: spoderman
  strategy:
    type: Recreate
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: spoderman
    spec:
      containers:
        - name: spoderman
          image: {{ .Values.apps.spoderman.deployment.image }}
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/app/config"
              name: config
              readOnly: true
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 256Mi
              cpu: 0.5
            limits:
              memory: 512Mi
              cpu: 1
      volumes:
        - name: config
          secret:
            secretName: config
            optional: false
            items:
              - key: config
                path: config.yaml
