apiVersion: apps/v1
kind: Deployment
metadata:
  name: spoderman
spec:
  selector:
    matchLabels:
      app: spoderman
  strategy:
    type: Recreate
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: spoderman
    spec:
      containers:
        - name: spoderman
          image: docker.pkg.github.com/voidpointergroup/spoderman/spoderman:{{ .Values.apps.spoderman.deployment.image.tag }}
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/app/config"
              name: config
              readOnly: true
          ports:
            - containerPort: 8080
      volumes:
        - name: config
          secret:
            secretName: config
            optional: false
            items:
              - key: config
                path: config.yaml
