apiVersion: v1
kind: Secret
metadata:
  name: config
type: Opaque
stringData:
  config: |-
    version: 0.1.0

    server:
      address: "0.0.0.0:8080"
      heartbeat_interval_sec: 10
      connection_timeout_sec: 31
      stats_interval_sec: 10
      max_out_message_size: 262144 # 256kb

    redis:
      endpoint: "redis://spoderman-redis-master:6379"

    routes:
      rules_engine:
        endpoint: "http://dss-rules-engine:8080"
        headers:
          Authorization: dss-rules-engine-key
      authorizer:
        endpoint: "http://dss-authorizer:8080"
        headers:
          Authorization: dss-authorizer-key
      connect:
        endpoint: "http://dss-connect:8080"
        headers:
          Authorization: dss-connect-key
      disconnect:
        endpoint: "http://dss-disconnect:8080"
        headers:
          Authorization: dss-disconnect-key
