---
apiVersion: hydrogen.voidpointergroup.com/v1
kind: Gateway
metadata:
  name: gw-1
  namespace: hydrogen
spec:
  replicas: 2
---
apiVersion: hydrogen.voidpointergroup.com/v1
kind: Mproc
metadata:
  name: mproc-1
  namespace: hydrogen
spec:
  hpa:
    min: 2
    max: 10
    cpu: 50
  config:
    inline: |-
      version: 0.1.0
      queue:
        nats:
          endpoint: "nats://hydrogen-nats:4222"
          stream: "05b42eec8d834f4f8be226825fd7fecf"
      engine_mode:
        regex:
          rules:
            - regex: "^!"
              route:
                endpoint: "http://hydrogen-dss-sink-b:8080"
                headers:
                  Authorization: dss-sink-b-key
            - regex: ".*"
              route:
                endpoint: "http://hydrogen-dss-sink-a:8080"
                headers:
                  Authorization: dss-sink-a-key
---

