VERSION 0.6

rust:
  FROM debian:bullseye
  ARG toolchain
  RUN [ ! -z "$toolchain" ] || exit 1
  RUN apt update && apt upgrade
  RUN apt install gcc make build-essential curl -y
  RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $toolchain
  ENV PATH=/root/.cargo/bin:"$PATH"

spoderman:
  FROM +rust
  WORKDIR /app
  COPY ./spoderman .

image:
  ARG toolchain
  ARG version
  ARG tag
  FROM DOCKERFILE \
    -f ./spoderman/docker/Dockerfile \
    --build-arg toolchain=$toolchain \
    --build-arg version=$version \
    ./spoderman
  SAVE IMAGE $tag

fmt:
  FROM +spoderman
  RUN cargo fmt --all -- --check

test:
  FROM +spoderman
  ARG features
  RUN cargo test $features

