{{- if .Values.apps.support.dummysetup.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dss-disconnect
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-dss-disconnect
  strategy:
    type: Recreate
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-dss-disconnect
    spec:
      containers:
        - name: dss-disconnect
          image: python:3.10-buster
          imagePullPolicy: IfNotPresent
          command: ["python", "/app/code/code.py"]
          volumeMounts:
            - mountPath: "/app/code"
              name: code
              readOnly: true
          ports:
            - containerPort: 8080
      volumes:
        - name: code
          configMap:
            name: {{ .Release.Name }}-dss-disconnect-code
            optional: false
            items:
              - key: code
                path: code.py
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-dss-disconnect-code
data:
  code: |-
    # Python 3 server example
    from http.server import BaseHTTPRequestHandler, HTTPServer
    from json import JSONDecoder, JSONEncoder

    hostName = "0.0.0.0"
    serverPort = 8080

    class Server(BaseHTTPRequestHandler):
        def do_POST(self):
            if self.headers.get('Authorization') != 'dss-disconnect-key':
                self.send_response(500)
                self.end_headers()
                return

            self.send_response(200)
            self.end_headers()

    if __name__ == "__main__":
        webServer = HTTPServer((hostName, serverPort), Server)
        print("Server started http://%s:%s" % (hostName, serverPort), flush=True)

        try:
            webServer.serve_forever()
        except KeyboardInterrupt:
            pass

        webServer.server_close()
        print("Server stopped.", flush=True)
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dss-disconnect
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Release.Name }}-dss-disconnect
{{ end }}
