{{- if .Values.apps.support.dummysetup.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dss-sink-b
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-dss-sink-b
  strategy:
    type: Recreate
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-dss-sink-b
    spec:
      containers:
        - name: dss-sink-b
          image: python:3.10-buster
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c", "pip install requests && python /app/code/code.py"]
          volumeMounts:
            - mountPath: "/app/code"
              name: code
              readOnly: true
          ports:
            - containerPort: 8080
      volumes:
        - name: code
          configMap:
            name: {{ .Release.Name }}-dss-sink-b-code
            optional: false
            items:
              - key: code
                path: code.py
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-dss-sink-b-code
data:
  code: |-
    # Python 3 server example
    from http.server import BaseHTTPRequestHandler, HTTPServer
    from json import JSONDecoder, JSONEncoder
    import requests

    hostName = "0.0.0.0"
    serverPort = 8080

    class Server(BaseHTTPRequestHandler):
        def do_POST(self):
            if self.headers.get('Authorization') != 'dss-sink-b-key':
                self.send_response(500)
                self.end_headers()
                return

            body = JSONDecoder().decode(self.rfile.read(int(self.headers['Content-Length'])).decode('UTF-8'))
            print(body, flush=True)

            r = requests.post(f'http://{{ tpl .Release.Name . }}-spoderman:8080/connections/{body["connection_id"]}/_send', data=f'command: {body["message"]} not found')
            print(r.text)

            self.send_response(200)
            self.send_header("Content-type", "text/plain")
            self.end_headers()

    if __name__ == "__main__":
        webServer = HTTPServer((hostName, serverPort), Server)
        print("Server started http://%s:%s" % (hostName, serverPort), flush=True)

        try:
            webServer.serve_forever()
        except KeyboardInterrupt:
            pass

        webServer.server_close()
        print("Server stopped.", flush=True)

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dss-sink-b
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Release.Name }}-dss-sink-b
{{ end }}
