apps:
  gateway:
    enabled: true
    service:
      type: ClusterIP
      port: 8080
    deployment:
      revisions: 0
      strategy:
        type: Recreate
      image:
        ref: "harbor.chinook.k8s.voidpointergroup.com/hydrogen/hydrogen-gateway:nightly"
        pull_policy: IfNotPresent
    hpa:
      min: 1
      max: 1
      cpu_percentage: 50
    secrets:
      config:
        config: |-
          version: 0.1.0

          server:
            address: "0.0.0.0:8080"
            heartbeat_interval_sec: 10
            connection_timeout_sec: 31
            stats_interval_sec: 10
            max_out_message_size: 262144 # 256kb

          nats:
            endpoint: "nats://hydrogen-nats:4222"
            stream: client
          redis:
            endpoint: "redis://hydrogen-redis-master:6379"

          routes:
            authorizer:
              endpoint: "http://hydrogen-dss-authorizer:8080"
              headers:
                Authorization: dss-authorizer-key
            connect:
              endpoint: "http://hydrogen-dss-connect:8080"
              headers:
                Authorization: dss-connect-key
            disconnect:
              endpoint: "http://hydrogen-dss-disconnect:8080"
              headers:
                Authorization: dss-disconnect-key
  mproc:
    enabled: true
    deployment:
      revisions: 0
      strategy:
        type: Recreate
      image:
        ref: "harbor.chinook.k8s.voidpointergroup.com/hydrogen/hydrogen-mproc:nightly"
        pull_policy: IfNotPresent
    hpa:
      min: 1
      max: 1
      cpu_percentage: 50
    secrets:
      config:
        config: |-
          version: 0.1.0

          queue:
            nats:
              endpoint: "nats://hydrogen-nats:4222"
              stream: client

          engine_mode:
            regex:
              rules:
                - regex: "^!"
                  route:
                    endpoint: "http://hydrogen-dss-sink-b:8080"
                    headers:
                      Authorization: dss-sink-b-key
                - regex: ".*"
                  route:
                    endpoint: "http://hydrogen-dss-sink-a:8080"
                    headers:
                      Authorization: dss-sink-a-key
            # dss:
            #   rules_engine:
            #     endpoint: "http://hydrogen-dss-rules-engine:8080"
            #     headers:
            #       Authorization: dss-rules-engine-key

  support:
    dummysetup:
      enabled: true

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      size: 2Gi
      existingClaim: ""

nats:
  enabled: true
  nats:
    jetstream:
      enabled: true
      memStorage:
        enabled: true
        size: 1Gi
      fileStorage:
        enabled: true
        size: 4Gi
  cluster:
    enabled: false
    replicas: 3
