apps:
  gateway:
    service:
      type: ClusterIP
      port: 8080
    deployment:
      revisions: 0
      strategy:
        type: Recreate
      image:
        ref: "harbor.chinook.k8s.voidpointergroup.com/spoderman/spoderman-gateway:nightly"
        pullpolicy: Always
    secrets:
      config:
        config: |-
          version: 0.1.0

          server:
            address: "0.0.0.0:8080"
            heartbeat_interval_sec: 10
            connection_timeout_sec: 31
            stats_interval_sec: 10
            max_out_message_size: 262144 # 256kb

          nats:
            endpoint: "redis://spoderman-nats:4222"
          redis:
            endpoint: "redis://spoderman-redis-master:6379"

          routes:
            authorizer:
              endpoint: "http://spoderman-dss-authorizer:8080"
              headers:
                Authorization: dss-authorizer-key
            connect:
              endpoint: "http://spoderman-dss-connect:8080"
              headers:
                Authorization: dss-connect-key
            disconnect:
              endpoint: "http://spoderman-dss-disconnect:8080"
              headers:
                Authorization: dss-disconnect-key
  worker:
    deployment:
      revisions: 0
      strategy:
        type: Recreate
      image:
        ref: "harbor.chinook.k8s.voidpointergroup.com/spoderman/spoderman-worker:nightly"
        pullpolicy: Always
    secrets:
      config:
        config: |-
          version: 0.1.0

          nats:
            endpoint: "redis://spoderman-nats:4222"

          routes:
            rules_engine:
              endpoint: "http://spoderman-dss-rules_engine:8080"
              headers:
                Authorization: dss-authorizer-key
  support:
    dummysetup:
      enabled: true

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      size: 2Gi
      existingClaim: ""

nats:
  enabled: true
  nats:
    jetstream:
      enabled: true
      memStorage:
        enabled: true
        size: 1Gi
      fileStorage:
        enabled: true
        size: 4Gi
  cluster:
    enabled: false
    replicas: 3
