apps:
  operator:
    enabled: true
    deployment:
      revisions: 0
      strategy:
        type: Recreate
      image:
        ref: "harbor.chinook.k8s.voidpointergroup.com/hydrogen/hydrogen-operator:nightly"
        pull_policy: Always
    secrets:
      config:
        config: |-
          version: 0.1.0

  support:
    dummysetup:
      enabled: true

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      size: 2Gi
      existingClaim: ""

nats:
  enabled: true
  nats:
    jetstream:
      enabled: true
      memStorage:
        enabled: true
        size: 1Gi
      fileStorage:
        enabled: true
        size: 4Gi
  cluster:
    enabled: false
    replicas: 3
