apps:
  spoderman:
    deployment:
      image:
        tag: nightly
  support:
    dummysetup:
      enabled: true

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      size: 2Gi
      existingClaim: ""
