apps:
  spoderman:
    deployment:
      image: "harbor.chinook.k8s.voidpointergroup.com/spoderman/spoderman:nightly"
    hpa:
      min: 1
      max: 3
      threshhold:
        cpu: 0.75
        ram: 768Mi

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      size: 2Gi
      existingClaim: ""
