---
apiVersion: hydrogen.voidpointergroup.com/v1
kind: Mproc
metadata:
  name: echo-mproc
  namespace: hydrogen
spec:
  hpa:
    min: 2
    max: 10
    cpu: 50
  config:
    inline: |-
      version: 0.1.0
      stream:
        endpoint: "nats://hydrogen-nats:4222"
        name: "05b42eec8d834f4f8be226825fd7fecf"
        consumer_name: "0x01"
      engine_mode:
        regex:
          rules:
            - regex: "^!"
              route:
                endpoint: "http://hydrogen-dss-sink-b:8080"
                headers:
                  Authorization: dss-sink-b-key
                  x-return-to: "http://echo-gateway-1:8080"
            - regex: ".*"
              route:
                endpoint: "http://hydrogen-dss-sink-a:8080"
                headers:
                  Authorization: dss-sink-a-key
                  x-return-to: "http://echo-gateway-1:8080"
---
apiVersion: hydrogen.voidpointergroup.com/v1
kind: Gateway
metadata:
  name: echo-gateway-1
  namespace: hydrogen
spec:
  config:
    inline: |-
      version: 0.1.0
      server:
        address: "0.0.0.0:8080"
        heartbeat_interval_sec: 10
        connection_timeout_sec: 31
        stats_interval_sec: 10
        max_out_message_size: 262144 # 256kb
      nats:
        endpoint: "nats://hydrogen-nats:4222"
        stream: "05b42eec8d834f4f8be226825fd7fecf"
      redis:
        endpoint: "redis://hydrogen-redis-master:6379"
      routes:
        authorizer:
          endpoint: "http://hydrogen-dss-authorizer:8080"
          headers:
            Authorization: dss-authorizer-key
        connect:
          endpoint: "http://hydrogen-dss-connect:8080"
          headers:
            Authorization: dss-connect-key
        disconnect:
          endpoint: "http://hydrogen-dss-disconnect:8080"
          headers:
            Authorization: dss-disconnect-key
  hpa:
    cpu: 50
    max: 4
    min: 2
---

