{{- if .Values.apps.gateway.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-spoderman-gateway-config
type: Opaque
stringData:
  {{- toYaml .Values.apps.gateway.secrets.config | nindent 2 }}
{{ end }}
