/// Struct corresponding to the Specification (`spec`) part of the `Echo`
/// resource, directly reflects context of the `echoes.example.com.yaml` file to
/// be found in this repository. The `Echo` struct will be generated by the
/// `CustomResource` derive macro.
#[derive(kube::CustomResource, serde::Serialize, serde::Deserialize, Debug, PartialEq, Clone, schemars::JsonSchema)]
#[kube(
    group = "voidpointergroup.com",
    version = "v1",
    kind = "Echo",
    plural = "Echoes",
    derive = "PartialEq",
    namespaced
)]
pub struct EchoSpec {
    pub replicas: i32,
}
