{{- if .Values.apps.mproc.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-spoderman-mproc
spec:
  maxReplicas: {{ .Values.apps.mproc.hpa.max }}
  minReplicas: {{ .Values.apps.mproc.hpa.max }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-spoderman-mproc
  targetCPUUtilizationPercentage: {{ .Values.apps.mproc.hpa.cpu_percentage }}
{{ end }}
