---
doctype: article
title: Home
date: 2021-10-10
draft: false
weight: 1
---
:toc:

== Home

include::./content/parts/status-table.adoc.part[]

`socketboss` is a (very, very much) work in progress websocket API gateway that abstracts websocket connections from services while still allowing bidirectional communication.

[plantuml]
....

== startup ==

loop [permanent_thread]
    socketboss -> redis : ask for messages for connections
    redis --> socketboss : message for connection
    socketboss -> client : message
end

== connect == 

client -> socketboss : connect

socketboss -> authorizer : authorize
alt [error]
    authorizer --> socketboss : code != 200 (disallow)
    socketboss --> client : reject
    destroy client
end
authorizer --> socketboss : allow (code == 200)

socketboss -> connect : onConnect
alt [error]
    connect --> socketboss : code != 200 (error)
    socketboss --> client : reject
    destroy client
end
connect --> socketboss : ok (code == 200)

socketboss -> redis : register connection on instance
redis --> socketboss

socketboss --> client : accept

== client sends message ==

client -> socketboss : send message
socketboss -> rules_engine : request route
alt [success]
    rules_engine --> socketboss : route
    socketboss --> message_destination : forward message
    alt [success]
        message_destination --> socketboss : ok (code == 200)
    else [error]
        message_destination --> socketboss : code != 200 (error)
    end

else [error]
    rules_engine --> socketboss : code != 200 (error)
end

== service sends message to connection ==

message_destination -> socketboss : send message to connection
socketboss -> redis : lookup instance for connection
redis --> socketboss : instance id
socketboss -> redis : publish message for connection on instance

== disconnect ==

client -> socketboss : disconnect

socketboss -> disconnect : disconnect
disconnect --> socketboss

....
