apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: echoes.voidpointergroup.com
spec:
  group: voidpointergroup.com
  scope: Namespaced
  names:
    kind: echo
    singular: echo
    plural: echoes
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                  format: int32
              required: ["replicas"]
---
apiVersion: voidpointergroup.com/v1
kind: echo
metadata:
  name: echo-test-1
  namespace: hydrogen
spec:
  replicas: 2
---

