{{- if .Values.apps.operator.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-hydrogen-operator-config
type: Opaque
stringData:
  {{- toYaml .Values.apps.operator.secrets.config | nindent 2 }}
{{ end }}
