name: release (scheduled nightly)
on:
  workflow_dispatch:
  # daily at 12am
  schedule: [{cron: "0 0 * * *"}]

jobs:
  publish-ghcr:
    name: publish to ghcr (nightly)
    runs-on: ubuntu-latest
    steps:
    - name: install tools
      run: |
        sudo apt-get install build-essential
        rustup default stable
        pip install invoke
    - uses: actions/checkout@v2
    - name: build image
      working-directory: ./spoderman
      run: invoke docker.build --tag=voidpointergroup/spoderman:nightly
    - name: publish
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${GITHUB_ACTOR} --password-stdin
        docker tag voidpointergroup/spoderman:nightly docker.pkg.github.com/voidpointergroup/spoderman/spoderman:nightly
        docker push docker.pkg.github.com/voidpointergroup/spoderman/spoderman:nightly
