name: nightly
on:
  workflow_dispatch:
  schedule: [{cron: "0 0 * * *"}]
  push:

jobs:
  build:
    name: build image
    runs-on: ubuntu-latest
    steps:
      - name: install tools
        run: |
          sudo apt-get install build-essential
          rustup default stable
          pip install invoke
      - uses: actions/checkout@v2
      - name: build image
        working-directory: ./spoderman
        run: invoke docker.build --tag=voidpointergroup/spoderman:nightly
      - name: save image
        working-directory: ./spoderman
        run: docker save voidpointergroup/spoderman:nightly | gzip > docker/image.tar.gz
      - name: cache image
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v2
        with:
          name: spoderman
          path: ./spoderman/docker/image.tar.gz

  publish-ghcr:
    name: publish to ghcr (nightly)
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: download image
        uses: actions/download-artifact@v2
        with:
          name: spoderman
          path: ./spoderman/docker/image.tar.gz
      - name: import image
        working-directory: ./spoderman
        run: docker load --input ./docker/image.tar.gz
      - name: publish
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${GITHUB_ACTOR} --password-stdin
          docker tag voidpointergroup/spoderman:nightly docker.pkg.github.com/voidpointergroup/spoderman/spoderman:nightly
          docker push docker.pkg.github.com/voidpointergroup/spoderman/spoderman:nightly
      - name: run trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.pkg.github.com/voidpointergroup/spoderman/spoderman:nightly'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
      - name: upload trivy results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
