name: release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag for the image.'
        required: true
      version:
        description: 'The version of the application inside the image.'
        required: true

jobs:
  publish-ghcr:
    name: publish to ghcr (${{ github.event.inputs.version }})
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install earthly
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.6.14/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: fmt
        run: earthly +image --toolchain=nightly --version="${{ github.event.inputs.version }}" --tag="voidpointergroup/spoderman:${{ github.event.inputs.tag }}"
      - name: publish
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${GITHUB_ACTOR} --password-stdin
          docker tag voidpointergroup/spoderman:${{ github.event.inputs.tag }} docker.pkg.github.com/voidpointergroup/spoderman/spoderman:${{ github.event.inputs.tag }}
          docker tag voidpointergroup/spoderman:${{ github.event.inputs.tag }} docker.pkg.github.com/voidpointergroup/spoderman/spoderman:latest
          docker push docker.pkg.github.com/voidpointergroup/spoderman/spoderman:${{ github.event.inputs.tag }}
          docker push docker.pkg.github.com/voidpointergroup/spoderman/spoderman:latest
