name: release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true

jobs:
  publish-ghcr:
    name: publish to ghcr (${{ github.event.inputs.version }})
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - name: install tools
      run: |
        sudo apt-get install build-essential
        rustup default stable
        pip install invoke
    - uses: actions/checkout@v1
    - name: build image
      working-directory: ./spoderman
      run: invoke docker.build --tag=voidpointergroup/spoderman:${{ github.event.inputs.version }}
    - name: publish
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${GITHUB_ACTOR} --password-stdin
        docker tag voidpointergroup/spoderman:${{ github.event.inputs.version }} docker.pkg.github.com/voidpointergroup/spoderman/spoderman:${{ github.event.inputs.version }}
        docker push docker.pkg.github.com/voidpointergroup/spoderman/spoderman:${{ github.event.inputs.version }}
